version: '3.5'
services:
  app:
    build: .
    ports:
     - "9000:9000"
    environment:
      NODE_ENV: compose
      PORT: 9000
      JWT_SECRET: secret
      MONGO_URI: 'n/a'
    command:
     - "npm"
     - "run"
     - "test"
